
#----------Instillinger: Boks på toppen av side----------------------------------------------------------------------
bilde: https://github.com/uit-econ/hovedside/blob/main/assets/img/Bed-1004.jpg?raw=true #Emnebilde
name: Sok-1400 Introduksjon til python #Emnetittel
semester: Høst 2021



#--------------Avanserte instillinger---------------------------------------------------------------------
topbox-farge: 00617f

contentbox-farge: ffff;
contentbox-skygge: 0px 0px 100px 0px rgba(50, 50, 50, 1)

bakgrunn: https://raw.githubusercontent.com/uit-econ/emneside-alt/main/assets/img/emneside-bakgrunn1.jpg
bakgrunn-farge: 

#Farge tekst
primaerfarge: 007396 #Farge overskrifter
sekundaerfarge: #Farge generell tekst
linkfarge: f2a900 #Farge linker

uitlogo: https://raw.githubusercontent.com/uit-econ/emneside-alt/main/assets/img/UiT_Logo_Bok_Hvit.png
title: null #Skal stå tom



#-------------IKKE SLETT---------------------------------------------------------------------
theme: jekyll-theme-primer
markdown: kramdown
kramdown:
   auto_ids: true
